name = "ai-hair-studio"
pages_build_output_dir = "out"
compatibility_date = "2026-07-12"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "ai-hair-db"
database_id = "38af2f56-013b-4139-8d2e-0541e98f0091"
